version: '3'

services:
  banana-vision-be-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: banana-vision-manager
    ports:
      - "8000:8000"
    env_file: .env 
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload #--workers 1
    networks:
      - cmu_msai_network
    volumes:
      - ./app:/usr/src/app/app 
      
networks:
  cmu_msai_network:
    driver: bridge